# Generated by Django 5.2.17 on 2026-10-07 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.instrument'),
        ),
    ]
