# Generated by Django 4.2.29 on 2026-10-09 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_alter_image_instrument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='name',
        ),
    ]
