# Generated by Django 6.0.6 on 2026-08-18 22:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_name', models.CharField(blank=True, max_length=22, null=True)),
                ('indexed_name', models.CharField(blank=True, max_length=77, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_name', models.CharField(blank=True, max_length=22)),
                ('indexed_name', models.CharField(blank=True, max_length=77, null=True)),
                ('first_released', models.IntegerField(default=0)),
                ('compilation', models.BooleanField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttl.artist')),
            ],
            options={
                'ordering': ['indexed_name'],
            },
        ),
        migrations.CreateModel(
            name='Listen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen_date', models.DateField(default=datetime.datetime(2026, 8, 18, 22, 54, 46, 409712))),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttl.title')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('alt', models.CharField(max_length=255)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttl.title')),
            ],
        ),
        migrations.CreateModel(
            name='Title_medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=55, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttl.medium')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttl.title')),
            ],
        ),
    ]
