# Generated by Django 4.2.29 on 2026-09-15 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listen',
            name='listen_date',
            field=models.DateField(default=datetime.datetime(2026, 9, 15, 20, 44, 20, 43291)),
        ),
    ]
