# Generated by Django 6.0.6 on 2026-10-05 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttl', '0003_alter_listen_listen_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listen',
            name='listen_date',
            field=models.DateField(default=datetime.datetime(2026, 10, 5, 13, 12, 54, 17655)),
        ),
    ]
