# Generated by Django 6.0.6 on 2026-10-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttl', '0004_alter_listen_listen_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listen',
            name='listen_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
