# Generated by Django 6.0.6 on 2026-09-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk', '0002_remove_booking_name_booking_event_name_booking_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
    ]
