# Generated by Django 4.2.29 on 2026-09-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk', '0004_destination_flight_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
