# Generated by Django 6.0.6 on 2026-08-18 16:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('long_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtr', models.DateField(default=datetime.date(2026, 8, 18))),
                ('tm', models.TimeField(null=True)),
                ('dst', models.FloatField(null=True)),
                ('av', models.FloatField(null=True)),
                ('mx', models.FloatField(null=True)),
                ('odo', models.IntegerField(null=True)),
                ('route', models.TextField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bike', models.ForeignKey(default='9', on_delete=django.db.models.deletion.PROTECT, to='bikes.bike')),
            ],
        ),
        migrations.CreateModel(
            name='RidePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm', models.TimeField(null=True)),
                ('dst', models.FloatField(null=True)),
                ('av', models.FloatField(null=True)),
                ('max', models.FloatField(null=True)),
                ('odo', models.IntegerField(null=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rides.point')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rides.ride')),
            ],
        ),
    ]
