# Generated by Django 4.2.29 on 2026-09-15 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dtr',
            field=models.DateField(default=datetime.date(2026, 9, 15)),
        ),
    ]
