# Generated by Django 6.0.6 on 2026-10-05 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_ride_dtr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dtr',
            field=models.DateField(default=datetime.date(2026, 10, 5)),
        ),
    ]
