# Generated by Django 5.2.17 on 2026-10-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_ride_dtr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dtr',
            field=models.DateField(),
        ),
    ]
