# Generated by Django 6.0.6 on 2026-08-18 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name_plural': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('notes', models.CharField(blank=True, null=True, verbose_name=155)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(blank=True, choices=[('D', 'Daily'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('Y', 'Yearly')], max_length=1, null=True)),
                ('vendor_name', models.CharField(blank=True, null=True, verbose_name='non recurring vendor')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='date on receipt')),
                ('statement_date', models.DateField(blank=True, null=True, verbose_name='date on statement')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('cr_dr', models.SmallIntegerField(default='-1')),
                ('cheque_no', models.CharField(blank=True, max_length=22, null=True, verbose_name='cheque no')),
                ('booking', models.CharField(blank=True, max_length=22, null=True, verbose_name='booking ref')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('user_created', models.CharField(default='sysgen', max_length=22, verbose_name='user created')),
                ('date_amended', models.DateTimeField(blank=True, null=True, verbose_name='date amended')),
                ('user_amended', models.CharField(blank=True, max_length=22, null=True, verbose_name='user amended')),
                ('project_name', models.CharField(blank=True, max_length=55, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True, verbose_name='date of transaction')),
                ('account', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='tr.account')),
                ('branch', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tr.branch')),
                ('payment_type', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr.payment_type')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr.project')),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr.reader')),
                ('transaction_type', models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='tr.transaction_type')),
                ('vendor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='tr.vendor')),
            ],
            options={
                'ordering': ['-statement_date'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr.vendor'),
        ),
    ]
