# Generated by Django 5.1.2 on 2024-12-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='branch',
        ),
    ]
