# Generated by Django 5.1.2 on 2024-12-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0002_rename_city_branch_rename_city_person_branch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='branch',
            new_name='city',
        ),
    ]
