# Generated by Django 5.1.2 on 2024-12-24 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0004_vendor_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr.branch'),
        ),
        migrations.AddField(
            model_name='person',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr.vendor'),
        ),
    ]
