# Generated by Django 5.1.2 on 2024-12-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0005_person_branch_person_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='notes',
            field=models.CharField(blank=True, null=True, verbose_name=155),
        ),
    ]
