# Generated by Django 5.1.2 on 2024-12-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0006_vendor_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=155),
        ),
    ]
