# Generated by Django 5.1.2 on 2024-12-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0007_alter_vendor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='country',
            new_name='vendor',
        ),
    ]
