# Generated by Django 5.1.2 on 2024-12-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0008_rename_country_branch_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
