# Generated by Django 5.1.2 on 2024-12-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0009_alter_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
    ]
