# Generated by Django 5.1.2 on 2024-12-28 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0010_remove_person_city_remove_person_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Tran_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_type', models.CharField(max_length=55)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr.branch'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='date on receipt')),
                ('statement_date', models.DateField(blank=True, null=True, verbose_name='date on statement')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('cr_dr', models.SmallIntegerField(default='-1')),
                ('cheque_no', models.CharField(blank=True, max_length=22, null=True, verbose_name='cheque no')),
                ('booking', models.CharField(blank=True, max_length=22, null=True, verbose_name='booking ref')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('user_created', models.CharField(default='sysgen', max_length=22, verbose_name='user created')),
                ('date_amended', models.DateTimeField(auto_now=True, null=True, verbose_name='date amended')),
                ('user_amended', models.CharField(blank=True, max_length=22, null=True, verbose_name='user amended')),
                ('project', models.CharField(blank=True, max_length=55, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True, verbose_name='date of transaction')),
                ('account', models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='tr.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tr.branch')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tr.payment_type')),
                ('tran_type', models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='tr.tran_type')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tr.vendor')),
            ],
        ),
    ]
