# Generated by Django 5.1.2 on 2024-12-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0011_account_payment_type_tran_type_alter_person_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='payment_type',
            old_name='payment_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tran_type',
            old_name='tran_type',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
