# Generated by Django 5.1.2 on 2024-12-28 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0012_rename_account_name_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.SET_DEFAULT, to='tr.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr.branch'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr.payment_type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tran_type',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.SET_DEFAULT, to='tr.tran_type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr.vendor'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr.reader'),
        ),
    ]
