# Generated by Django 5.1.2 on 2024-12-30 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0013_reader_alter_transaction_account_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tran_type',
            new_name='Transaction_type',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='tran_type',
            new_name='transaction_type',
        ),
    ]
