# Generated by Django 5.1.2 on 2024-12-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0014_rename_tran_type_transaction_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
