# Generated by Django 5.0.11 on 2025-02-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0015_delete_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'branches'},
        ),
    ]
