# Generated by Django 4.2.11 on 2025-10-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0017_alter_transaction_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subscription',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
