# Generated by Django 4.2.11 on 2025-10-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0018_transaction_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Training'), ('2', 'Tournament'), ('3', 'Coaching')], default='1', max_length=1, null=True),
        ),
    ]
