# Generated by Django 4.2.11 on 2025-10-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0019_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Training'), ('2', 'Tournament'), ('3', 'Coaching')], max_length=1, null=True),
        ),
    ]
