# Generated by Django 4.2.11 on 2025-10-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0020_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='frequency',
            field=models.CharField(blank=True, choices=[('D', 'Daily'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=1, null=True),
        ),
    ]
