# Generated by Django 4.2.11 on 2025-10-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0021_remove_transaction_type_transaction_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='subscription',
        ),
    ]
