# Generated by Django 4.2.11 on 2025-10-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0022_remove_transaction_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction_type',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='frequency',
            field=models.CharField(blank=True, choices=[('D', 'Daily'), ('M', 'Monthly'), ('Q', 'Yearly'), ('Y', 'Yearly')], max_length=1, null=True),
        ),
    ]
