# Generated by Django 4.2.11 on 2025-11-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0023_alter_transaction_type_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='frequency',
            field=models.CharField(blank=True, choices=[('D', 'Daily'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('Y', 'Yearly')], max_length=1, null=True),
        ),
    ]
