# Generated by Django 4.2.11 on 2025-11-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0024_alter_transaction_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='project',
            new_name='project_name',
        ),
    ]
