# Generated by Django 4.2.11 on 2025-11-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0025_project_rename_project_transaction_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr.project'),
        ),
    ]
