# Generated by Django 4.2.11 on 2026-01-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0026_transaction_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_amended',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date amended'),
        ),
    ]
