# Generated by Django 4.2.29 on 2026-03-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0027_alter_transaction_date_amended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-statement_date']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor_single',
            field=models.CharField(blank=True, null=True, verbose_name='non recurring vendor'),
        ),
    ]
