# Generated by Django 4.2.29 on 2026-03-19 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0028_alter_transaction_options_transaction_vendor_single'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tr.branch'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tr.vendor'),
        ),
    ]
