# Generated by Django 4.2.29 on 2026-03-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0029_alter_transaction_branch_alter_transaction_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='vendor_single',
            new_name='vendor_name',
        ),
    ]
