# Generated by Django 4.2.11 on 2025-04-11 11:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(max_length=35)),
                ('manufacturer', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=35)),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3000)])),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('sold_price', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.manufacturer')),
                ('country_of_manufacture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.country')),
            ],
        ),
    ]
