# Generated by Django 6.0.6 on 2026-10-05 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Training'), ('2', 'Tournament'), ('3', 'Coaching'), ('4', 'Club')], default='4', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='venue',
            field=models.ForeignKey(blank=True, default=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fn.venue'),
        ),
    ]
