# Generated by Django 5.1.3 on 2025-01-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('1', 'Training'), ('2', 'Tournament'), ('3', 'Coaching')], default='1', max_length=1),
        ),
    ]
