# Generated by Django 5.1.3 on 2025-01-07 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0002_activity_extra_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='date_fenced',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
