# Generated by Django 5.1.3 on 2025-01-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0003_remove_activity_date_fenced_activity_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Training'), ('2', 'Tournament'), ('3', 'Coaching')], default='1', max_length=1, null=True),
        ),
    ]
