# Generated by Django 6.0.2 on 2026-02-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0005_event_activity_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=66),
        ),
    ]
