# Generated by Django 4.2.29 on 2026-08-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0006_alter_venue_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name']},
        ),
    ]
