@echo off
title  SANBARROW's VMX-BUILDER
COLOR f3
setlocal
if not exist  %temp%\vmx-builder md %temp%\vmx-builder

echo ####### generated by Ullis VM builder # > %temp%\vmx-builder\new.vmx
echo. >> %temp%\vmx-builder\new.vmx
echo.
echo ####### Identity ###################### >> %temp%\vmx-builder\new.vmx

:NICNAMESET

SET Nicname=

echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.
echo.
echo      Ullis VMX-builder 
echo      check http://sanbarrow.com/vmxbuilder.html for latest version
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo. 
echo     please enter the displayname 
echo.
echo     --------------------------------------------------------------- 
echo.
SET /P Nicname=
IF /I "%Nicname%"==""    GOTO NICNAMESET
echo displayName = "%Nicname%" >> %temp%\vmx-builder\new.vmx
GOTO NICNAMEDONE
ECHO "%Nicname%" is not valid. Please try again.
pause
GOTO NICNAMESET
:NICNAMEDONE
title  SANBARROW's VMX-BUILDER creating %Nicname%.vmx 
:DEVICESPRE
echo memsize = "256" 				> %temp%\vmx-builder\ram.vmx-part
echo config.version = "8" 			> %temp%\vmx-builder\hw.vmx-part     
echo virtualHW.version = "4" 			>> %temp%\vmx-builder\hw.vmx-part
echo scsi0.present = "FALSE" 			> %temp%\vmx-builder\scsi0.vmx-part
echo scsi1.present = "FALSE" 			> %temp%\vmx-builder\scsi1.vmx-part
echo ide0:0.present = "FALSE" 			> %temp%\vmx-builder\ide00.vmx-part
echo ide0:1.present = "FALSE" 			> %temp%\vmx-builder\ide01.vmx-part
echo ide1:0.present = "FALSE" 			> %temp%\vmx-builder\ide10.vmx-part
echo ide1:1.present = "FALSE" 			> %temp%\vmx-builder\ide11.vmx-part
echo usb.present = "FALSE" 			> %temp%\vmx-builder\usb.vmx-part
echo sound.present = "FALSE" 			> %temp%\vmx-builder\sound.vmx-part
echo ethernet0.present = "FALSE" 		> %temp%\vmx-builder\nic0.vmx-part
echo ethernet1.present = "FALSE" 		> %temp%\vmx-builder\nic1.vmx-part
echo ethernet2.present = "FALSE" 		> %temp%\vmx-builder\nic2.vmx-part
echo ethernet3.present = "FALSE" 		> %temp%\vmx-builder\nic3.vmx-part
echo ethernet0.virtualDev = "vlance" 		> %temp%\vmx-builder\nic0type.vmx-part
echo ethernet1.virtualDev = "vlance" 		> %temp%\vmx-builder\nic1type.vmx-part
echo ethernet2.virtualDev = "vlance" 		> %temp%\vmx-builder\nic2type.vmx-part
echo ethernet3.virtualDev = "vlance" 		> %temp%\vmx-builder\nic3type.vmx-part
echo guestOS = "win2000Pro"  			> %temp%\vmx-builder\guestOS.vmx-part  
echo numvcpus = "1" 				> %temp%\vmx-builder\cpu.vmx-part      
echo scsi0:0.present = "FALSE"			> %temp%\vmx-builder\scsi00.vmx-part
echo scsi0:1.present = "FALSE"			> %temp%\vmx-builder\scsi01.vmx-part 
echo scsi0:2.present = "FALSE"			> %temp%\vmx-builder\scsi02.vmx-part 
echo scsi0:3.present = "FALSE"			> %temp%\vmx-builder\scsi03.vmx-part 
echo scsi0:4.present = "FALSE"			> %temp%\vmx-builder\scsi04.vmx-part  
echo scsi0:5.present = "FALSE"			> %temp%\vmx-builder\scsi05.vmx-part 
echo scsi0:6.present = "FALSE"			> %temp%\vmx-builder\scsi06.vmx-part 
echo scsi1:0.present = "FALSE"			> %temp%\vmx-builder\scsi10.vmx-part  
echo scsi1:1.present = "FALSE"			> %temp%\vmx-builder\scsi11.vmx-part  
echo scsi1:2.present = "FALSE"			> %temp%\vmx-builder\scsi12.vmx-part  
echo scsi1:3.present = "FALSE"			> %temp%\vmx-builder\scsi13.vmx-part  
echo scsi1:4.present = "FALSE"			> %temp%\vmx-builder\scsi14.vmx-part  
echo scsi1:5.present = "FALSE"                  > %temp%\vmx-builder\scsi15.vmx-part 
echo scsi1:6.present = "FALSE"                  > %temp%\vmx-builder\scsi16.vmx-part 
echo floppy0.present = "FALSE" 			> %temp%\vmx-builder\floppy0.vmx-part     
echo floppy0.startConnected = "FALSE"           > %temp%\vmx-builder\floppy0boot.vmx-part 
echo floppy1.present = "FALSE"                  > %temp%\vmx-builder\floppy1.vmx-part 
echo floppy1.startConnected = "FALSE"           > %temp%\vmx-builder\floppy1boot.vmx-part 
echo parallel0.present = "FALSE" 		> %temp%\vmx-builder\parallel0.vmx-part
echo serial0.present = "FALSE" 			> %temp%\vmx-builder\serial0.vmx-part
echo serial1.present = "FALSE" 			> %temp%\vmx-builder\serial1.vmx-part
echo.					        > %temp%\vmx-builder\clusteroptions.vmx-part
echo.					        > %temp%\vmx-builder\logging.vmx-part
echo.					        > %temp%\vmx-builder\sharedfolders.vmx-part
echo.					        > %temp%\vmx-builder\interaction.vmx-part 
echo.                                           > %temp%\vmx-builder\debug.vmx-part    
echo isolation.tools.dnd.disable = "FALSE"      > %temp%\vmx-builder\dnd.vmx-part 
echo isolation.tools.copy.enable = "TRUE"       > %temp%\vmx-builder\copy.vmx-part 
echo isolation.tools.paste.enabled = "TRUE"     > %temp%\vmx-builder\paste.vmx-part 



:DEVICES     
SET Choice=  
        
echo. 
echo.
echo      Add existing disks, isos and floppies - 
echo.
echo.      
echo      s = SCSI-disks             i = IDE-disks           o = ISO
echo      --------------------------------------------------------------     
echo.
echo      Configure devices:
echo. 
echo      f = Floppies               d = Sound               u = USB
echo      n = Nics                   r = RAM
echo      c = SCSI-controllers
echo      -------------------------------------------------------------- 
echo.      
echo      h = configure virtual Hardware and set OS-type
echo      a = advanced options
echo.  
echo      -------------------------------------------------------------- 
echo      p = preview          w = write configuration       x = exit
echo.      
echo.
echo      --------------------------------------------------------------
echo.


SET /P Choice=
IF /I "%Choice%"=="c"    GOTO SCSI
IF /I "%Choice%"=="s"    GOTO ADDSCSI
IF /I "%Choice%"=="i"    GOTO ADDIDE
IF /I "%Choice%"=="o"    GOTO ADDCDROM
IF /I "%Choice%"=="4"    GOTO OSTYPE55
IF /I "%Choice%"=="f"    GOTO Floppy
IF /I "%Choice%"=="d"    GOTO SOUND
IF /I "%Choice%"=="u"    GOTO USBSET
IF /I "%Choice%"=="n"    GOTO NIC0SET
IF /I "%Choice%"=="r"    GOTO RAMSET
IF /I "%Choice%"=="w"    GOTO WRITE
IF /I "%Choice%"=="a"    GOTO ADVANCED
IF /I "%Choice%"=="p"    GOTO PREVIEW
IF /I "%Choice%"=="h"    GOTO SetHW
IF /I "%Choice%"=="x"    GOTO Done

ECHO "%Choice%" is not valid. Please try again.
pause
GOTO DEVICES

:Advanced

echo # Devices  >> %temp%\vmx-builder\new.vmx

SET Choice=

echo.
echo  ---SANBARROW.COM---------------------------------------------------------------
echo.
echo.
echo.
echo      Advanced options   
echo      --------------------------------------------------------------
echo.
echo      0 = set Nic-devicetypes
echo      1 = set number of CPUs
echo      2 = configure Cluster-options
echo      3 = Logfiles
echo      4 = interaction with the VM
echo      5 = shared folders
echo.
echo.
echo.
echo.
echo      x = exit

echo.
echo.
echo     ---------------------------------------------------------------
echo.


SET /P Choice=
IF /I "%Choice%"=="0"    GOTO NICADVANCED
IF /I "%Choice%"=="1"    GOTO CPU
IF /I "%Choice%"=="2"    GOTO CLUSTEROPTIONS
IF /I "%Choice%"=="3"    GOTO LOGGING
IF /I "%Choice%"=="4"    GOTO INTERACTION
IF /I "%Choice%"=="5"    GOTO SHAREDFOLDERS
IF /I "%Choice%"=="x"    GOTO DEVICES

ECHO "%Choice%" is not valid. Please try again.
pause
GOTO DEVICES

                     
:SetHW                                                                
SET Choice=                                                           
                                                                      
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo      please select the type of VM  
echo.
echo.
echo.
echo      0 = Virtual Hardware 2  use with  GSX 2.5 Workstation 3
echo      1 = Virtual Hardware 3  use with  GSX 3.x Workstation 4
echo      2 = Virtual Hardware 4  use with  Workstation 5
echo      3 = Virtual Hardware 4  use with  Workstation 5.5
echo.
echo.
echo.
echo     ---------------------------------------------------------------
echo.


SET /P Choice=

IF /I "%Choice%"=="0"    GOTO HW2
IF /I "%Choice%"=="1"    GOTO HW3
IF /I "%Choice%"=="2"    GOTO HW4
IF /I "%Choice%"=="3"    GOTO HW5

ECHO "%Choice%" is not valid. Please try again.
pause
GOTO SetHW



:HW2
echo config.version = "6" > %temp%\vmx-builder\hw.vmx-part
echo virtualHW.version = "2" >> %temp%\vmx-builder\hw.vmx-part
GOTO DEVICES

:HW3
echo config.version = "7" > %temp%\vmx-builder\hw.vmx-part
echo virtualHW.version = "3" >> %temp%\vmx-builder\hw.vmx-part
GOTO DEVICES

:HW4
echo config.version = "8" > %temp%\vmx-builder\hw.vmx-part
echo virtualHW.version = "4" >> %temp%\vmx-builder\hw.vmx-part
GOTO OSTYPE50


:HW5
echo config.version = "8" > %temp%\vmx-builder\hw.vmx-part
echo virtualHW.version = "4" >> %temp%\vmx-builder\hw.vmx-part
GOTO OSTYPE55



:INTERACTION
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo      Interaction with the VM 
echo.
echo      0 = drag'n'drop  disabled
echo      1 = drag'n'drop enabled 
echo.
echo      2 = paste enabled 
echo      3 = paste disabled
echo.
echo      4 = copy  enabled 
echo      5 = copy  disabled
echo.              
echo.
echo.
echo.
echo      x = done 
echo.
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="0"    GOTO INTERACTION0
IF /I "%Choice%"=="1"    GOTO INTERACTION1
IF /I "%Choice%"=="2"    GOTO INTERACTION2
IF /I "%Choice%"=="3"    GOTO INTERACTION3
IF /I "%Choice%"=="4"    GOTO INTERACTION4
IF /I "%Choice%"=="5"    GOTO INTERACTION5
IF /I "%Choice%"=="x"    GOTO INTERACTIONx

ECHO "%Choice%" is not valid. Please try again.
pause
GOTO INTERACTION
:INTERACTION0
echo isolation.tools.dnd.disable = "TRUE" > %temp%\vmx-builder\dnd.vmx-part
GOTO INTERACTION 
:INTERACTION1
echo isolation.tools.dnd.disable = "FALSE" > %temp%\vmx-builder\dnd.vmx-part
GOTO INTERACTION
:INTERACTION2
echo isolation.tools.paste.enabled = "TRUE" > %temp%\vmx-builder\paste.vmx-part
GOTO INTERACTION  
:INTERACTION3
echo isolation.tools.paste.enabled = "FALSE" > %temp%\vmx-builder\paste.vmx-part
GOTO INTERACTION
:INTERACTION4
echo isolation.tools.copy.enable = "TRUE" > %temp%\vmx-builder\copy.vmx-part
GOTO INTERACTION
:INTERACTION5
echo isolation.tools.copy.enable = "FALSE" > %temp%\vmx-builder\copy.vmx-part
GOTO INTERACTION 

:INTERACTIONx  
GOTO DEVICES


:RAMSET

SET Choice=

echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.
echo      Lets talk about RAM
echo      x = don't want no RAM
echo      0 = give me   64 MB 
echo      1 = give me   96 MB 
echo      2 = give me  128 MB
echo      3 = give me  256 MB
echo      4 = give me  384 MB
echo      5 = give me  512 MB
echo      6 = give me  640 MB
echo      7 = give me  768 MB
echo      8 = give me  896 MB
echo      9 = give me 1024 MB





echo.
echo.
echo     ---------------------------------------------------------------
echo.


SET /P Choice=
IF /I "%Choice%"=="x"    GOTO RAMX
IF /I "%Choice%"=="0"    GOTO RAMA
IF /I "%Choice%"=="1"    GOTO RAMB
IF /I "%Choice%"=="2"    GOTO RAMC
IF /I "%Choice%"=="3"    GOTO RAMD
IF /I "%Choice%"=="4"    GOTO RAME
IF /I "%Choice%"=="5"    GOTO RAMF
IF /I "%Choice%"=="6"    GOTO RAMG
IF /I "%Choice%"=="7"    GOTO RAMH
IF /I "%Choice%"=="8"    GOTO RAMI
IF /I "%Choice%"=="9"    GOTO RAMJ

ECHO "%Choice%" is not valid. Please try again.
pause
GOTO RAMSET

:RAMX
echo you must be kidding ...
pause
GOTO RAMSET

:RAMA
echo memsize = "64" > %temp%\vmx-builder\ram.vmx-part
GOTO RAMDONE

:RAMB
echo memsize = "96" > %temp%\vmx-builder\ram.vmx-part
GOTO RAMDONE

:RAMC
echo memsize = "128" > %temp%\vmx-builder\ram.vmx-part
GOTO RAMDONE

:RAMD
echo memsize = "256"  > %temp%\vmx-builder\ram.vmx-part
GOTO RAMDONE

:RAME
echo memsize = "384"  > %temp%\vmx-builder\ram.vmx-part
GOTO RAMDONE

:RAMF
echo memsize = "512"  > %temp%\vmx-builder\ram.vmx-part
GOTO RAMDONE

:RAMG
echo memsize = "640"  > %temp%\vmx-builder\ram.vmx-part
GOTO RAMDONE

:RAMH
echo memsize = "768"  > %temp%\vmx-builder\ram.vmx-part
GOTO RAMDONE

:RAMI
echo memsize = "896"  > %temp%\vmx-builder\ram.vmx-part
GOTO RAMDONE

:RAMJ
echo memsize = "1024"  > %temp%\vmx-builder\ram.vmx-part
GOTO RAMDONE

:RAMDONE
GOTO DEVICES

:SCSI
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo      select virtual hardware for SCSI-controllers
echo.
echo.
echo      0 = SCSI - no ... thanks
echo.
echo      1 = SCSI-controller 0 uses BUSLOGIC
echo      2 = SCSI-controller 0 uses LSILOGIC
echo.
echo      3 = SCSI-controller 1 uses BUSLOGIC
echo      4 = SCSI-controller 1 uses LSILOGIC
echo.
echo      x = done
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="0"    GOTO SCSI0
IF /I "%Choice%"=="1"    GOTO SCSI1
IF /I "%Choice%"=="2"    GOTO SCSI2
IF /I "%Choice%"=="3"    GOTO SCSI3
IF /I "%Choice%"=="4"    GOTO SCSI4
IF /I "%Choice%"=="x"    GOTO SCSIx
ECHO "%Choice%" is not valid. Please try again.
pause
GOTO SCSI
:SCSI0
echo scsi0.present = "FALSE" 		> %temp%\vmx-builder\scsi0.vmx-part  
echo scsi1.present = "FALSE" 		> %temp%\vmx-builder\scsi1.vmx-part
GOTO SCSI
:SCSI1
echo scsi0.present = "TRUE" 		 > %temp%\vmx-builder\scsi0.vmx-part
echo scsi0.virtualDev = "buslogic" 	>> %temp%\vmx-builder\scsi0.vmx-part
GOTO SCSI
:SCSI2
echo scsi0.present = "TRUE" 		 > %temp%\vmx-builder\scsi0.vmx-part
echo scsi0.virtualDev = "lsilogic" 	>> %temp%\vmx-builder\scsi0.vmx-part
GOTO SCSI 
:SCSI3
echo scsi1.present = "TRUE" 		 > %temp%\vmx-builder\scsi1.vmx-part         
echo scsi1.virtualDev = "buslogic" 	>> %temp%\vmx-builder\scsi1.vmx-part   
GOTO SCSI 
:SCSI4
echo scsi1.present = "TRUE" 		 > %temp%\vmx-builder\scsi1.vmx-part            
echo scsi1.virtualDev = "lsilogic" 	>> %temp%\vmx-builder\scsi1.vmx-part    
GOTO SCSI 
:SCSIx
GOTO DEVICES

:LOGGING
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo      Lets talk about LOGGING
echo.
echo.
echo      0 = disable logs
echo      1 = enable logs
echo      2 = log virtual machine progress periodically
echo.
echo.
echo      x = done
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="0"    GOTO LOGGINGA
IF /I "%Choice%"=="1"    GOTO LOGGINGB
IF /I "%Choice%"=="2"    GOTO LOGGINGC
IF /I "%Choice%"=="x"    GOTO LOGGINGx

ECHO "%Choice%" is not valid. Please try again.
pause
GOTO LOGGING
:LOGGINGA
echo logging = "TRUE" > %temp%\vmx-builder\logging.vmx-part
GOTO LOGGINGDONE
:LOGGINGB
echo logging = "TRUE" > %temp%\vmx-builder\logging.vmx-part
GOTO LOGGING
:LOGGINGC
echo monitor_control.log_vmsample = "TRUE" > %temp%\vmx-builder\logging.vmx-part
GOTO LOGGING
:LOGGINGx
:LOGGINGDONE
GOTO DEVICES

:SHAREDFOLDERS
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo      Lets talk about SHAREDFOLDERS
echo.
echo.
echo      0 = disable shared folders
echo      1 = enable shared folders
echo.
echo.
echo.
echo      x = done
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="0"    GOTO SHAREDFOLDERSA
IF /I "%Choice%"=="1"    GOTO SHAREDFOLDERSB
IF /I "%Choice%"=="x"    GOTO SHAREDFOLDERSx

ECHO "%Choice%" is not valid. Please try again.
pause
GOTO SHAREDFOLDERS
:SHAREDFOLDERSA
echo isolation.tools.hgfs.disable = "TRUE" > %temp%\vmx-builder\sharedfolders.vmx-part
GOTO SHAREDFOLDERSDONE
:SHAREDFOLDERSB
echo isolation.tools.hgfs.disable = "FALSE" > %temp%\vmx-builder\sharedfolders.vmx-part
GOTO SHAREDFOLDERS

:SHAREDFOLDERSx
:SHAREDFOLDERSDONE
GOTO DEVICES

:SOUND
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo      Lets talk about Sound
echo.
echo.
echo      0 = Sound - no ... thanks
echo      1 = use es1371
echo      2 = use sb16
echo      3 = use sb16 and enable OPL3/Yamaha Synth engine
echo.
echo      x = done
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="0"    GOTO SOUNDA
IF /I "%Choice%"=="1"    GOTO SOUNDB
IF /I "%Choice%"=="2"    GOTO SOUNDC
IF /I "%Choice%"=="3"    GOTO SOUNDD
IF /I "%Choice%"=="x"    GOTO DEVICES

ECHO "%Choice%" is not valid. Please try again.
pause
GOTO SOUNDSET
:SOUNDA
echo sound.present = "FALSE" > %temp%\vmx-builder\sound.vmx-part
GOTO SOUNDDONE
:SOUNDB
echo sound.present = "TRUE" > %temp%\vmx-builder\sound.vmx-part
echo sound.virtualDev = "es1371" >> %temp%\vmx-builder\sound.vmx-part
GOTO SOUND
:SOUNDC
echo sound.present = "TRUE" > %temp%\vmx-builder\sound.vmx-part
echo sound.virtualDev = "sb16" >> %temp%\vmx-builder\sound.vmx-part
GOTO SOUND
:SOUNDD
echo sound.present = "TRUE" > %temp%\vmx-builder\sound.vmx-part
echo sound.virtualDev = "sb16" >> %temp%\vmx-builder\sound.vmx-part
echo sound.synth.operational = "TRUE" >> %temp%\vmx-builder\sound.vmx-part
GOTO SOUND
:SOUNDDONE
GOTO DEVICES

:USBSET

SET Choice=

echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo      Lets talk about USB
echo.
echo.
echo.
echo      0 = USB - no ... thanks
echo      1 = USB would be nice
echo.
echo.
echo.
echo.
echo     ---------------------------------------------------------------
echo.


SET /P Choice=

IF /I "%Choice%"=="0"    GOTO USBA
IF /I "%Choice%"=="1"    GOTO USBB

ECHO "%Choice%" is not valid. Please try again.
pause
GOTO USBSET



:USBA
echo usb.present = "FALSE" > %temp%\vmx-builder\usb.vmx-part
GOTO USBDONE

:USBB
echo usb.present = "TRUE" > %temp%\vmx-builder\usb.vmx-part
GOTO USBDONE



:USBDONE
GOTO DEVICES

:NIC0SET

SET Choice=

echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.
echo      Lets talk about ethernet0
echo.
echo      x = NICs - no ... thanks
echo      0 = give me one in vmnet0
echo      1 = give me one in vmnet1
echo      2 = give me one in vmnet2
echo      3 = give me one in vmnet3
echo      4 = give me one in vmnet4
echo      5 = give me one in vmnet5
echo      6 = give me one in vmnet6
echo      7 = give me one in vmnet7
echo      8 = give me one in vmnet8
echo      9 = give me one in vmnet9

echo.
echo.
echo     ---------------------------------------------------------------
echo.


SET /P Choice=
IF /I "%Choice%"=="x"    GOTO DEVICES
IF /I "%Choice%"=="0"    GOTO NIC0A
IF /I "%Choice%"=="1"    GOTO NIC0B
IF /I "%Choice%"=="2"    GOTO NIC0C
IF /I "%Choice%"=="3"    GOTO NIC0D
IF /I "%Choice%"=="4"    GOTO NIC0E
IF /I "%Choice%"=="5"    GOTO NIC0F
IF /I "%Choice%"=="6"    GOTO NIC0G
IF /I "%Choice%"=="7"    GOTO NIC0H
IF /I "%Choice%"=="8"    GOTO NIC0I
IF /I "%Choice%"=="9"    GOTO NIC0J

ECHO "%Choice%" is not valid. Please try again.
pause
GOTO NIC0SET

:NIC0X
echo ethernet0.present = "FALSE" > %temp%\vmx-builder\nic0.vmx-part
GOTO NIC0DONE

:NIC0A
echo ethernet0.present = "TRUE" > %temp%\vmx-builder\nic0.vmx-part
echo ethernet0.vnet =  "VMnet0" >> %temp%\vmx-builder\nic0.vmx-part
GOTO NIC0DONE

:NIC0B
echo ethernet0.present = "TRUE"  > %temp%\vmx-builder\nic0.vmx-part
echo ethernet0.vnet =  "VMnet1" >> %temp%\vmx-builder\nic0.vmx-part
GOTO NIC0DONE

:NIC0C
echo ethernet0.present = "TRUE"  > %temp%\vmx-builder\nic0.vmx-part  
echo ethernet0.vnet =  "VMnet2" >> %temp%\vmx-builder\nic0.vmx-part  
GOTO NIC0DONE

:NIC0D
echo ethernet0.present = "TRUE"  > %temp%\vmx-builder\nic0.vmx-part  
echo ethernet0.vnet =  "VMnet3" >> %temp%\vmx-builder\nic0.vmx-part  
GOTO NIC0DONE

:NIC0E
echo ethernet0.present = "TRUE"  > %temp%\vmx-builder\nic0.vmx-part  
echo ethernet0.vnet =  "VMnet4" >> %temp%\vmx-builder\nic0.vmx-part  
GOTO NIC0DONE

:NIC0F
echo ethernet0.present = "TRUE"  > %temp%\vmx-builder\nic0.vmx-part  
echo ethernet0.vnet =  "VMnet5" >> %temp%\vmx-builder\nic0.vmx-part  
GOTO NIC0DONE

:NIC0G
echo ethernet0.present = "TRUE"  > %temp%\vmx-builder\nic0.vmx-part  
echo ethernet0.vnet =  "VMnet6" >> %temp%\vmx-builder\nic0.vmx-part  
GOTO NIC0DONE

:NIC0H
echo ethernet0.present = "TRUE"  > %temp%\vmx-builder\nic0.vmx-part  
echo ethernet0.vnet =  "VMnet7" >> %temp%\vmx-builder\nic0.vmx-part  
GOTO NIC0DONE

:NIC0I
echo ethernet0.present = "TRUE"  > %temp%\vmx-builder\nic0.vmx-part  
echo ethernet0.vnet =  "VMnet8" >> %temp%\vmx-builder\nic0.vmx-part  
GOTO NIC0DONE

:NIC0J
echo ethernet0.present = "TRUE"  > %temp%\vmx-builder\nic0.vmx-part  
echo ethernet0.vnet =  "VMnet9" >> %temp%\vmx-builder\nic0.vmx-part  
GOTO NIC0DONE

:NIC0DONE

:NIC1SET

SET Choice=

echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.
echo      Lets talk about ethernet1
echo.
echo      x = NIC 1 - no ... thanks
echo      0 = give me one in vmnet0
echo      1 = give me one in vmnet1
echo      2 = give me one in vmnet2
echo      3 = give me one in vmnet3
echo      4 = give me one in vmnet4
echo      5 = give me one in vmnet5
echo      6 = give me one in vmnet6
echo      7 = give me one in vmnet7
echo      8 = give me one in vmnet8
echo      9 = give me one in vmnet9

echo.
echo.
echo     ---------------------------------------------------------------
echo.


SET /P Choice=
IF /I "%Choice%"=="x"    GOTO DEVICES
IF /I "%Choice%"=="0"    GOTO NIC1A
IF /I "%Choice%"=="1"    GOTO NIC1B
IF /I "%Choice%"=="2"    GOTO NIC1C
IF /I "%Choice%"=="3"    GOTO NIC1D
IF /I "%Choice%"=="4"    GOTO NIC1E
IF /I "%Choice%"=="5"    GOTO NIC1F
IF /I "%Choice%"=="6"    GOTO NIC1G
IF /I "%Choice%"=="7"    GOTO NIC1H
IF /I "%Choice%"=="8"    GOTO NIC1I
IF /I "%Choice%"=="9"    GOTO NIC1J

ECHO "%Choice%" is not valid. Please try again.
pause
GOTO NIC1SET

:NIC1X
echo ethernet1.present = "FALSE" > %temp%\vmx-builder\nic1.vmx-part
GOTO NIC1DONE

:NIC1A
echo ethernet1.present = "TRUE"  > %temp%\vmx-builder\nic1.vmx-part  
echo ethernet1.vnet =  "VMnet0" >> %temp%\vmx-builder\nic1.vmx-part  
GOTO NIC1DONE

:NIC1B
echo ethernet1.present = "TRUE"  > %temp%\vmx-builder\nic1.vmx-part
echo ethernet1.vnet =  "VMnet1" >> %temp%\vmx-builder\nic1.vmx-part
GOTO NIC1DONE

:NIC1C
echo ethernet1.present = "TRUE"  > %temp%\vmx-builder\nic1.vmx-part
echo ethernet1.vnet =  "VMnet2" >> %temp%\vmx-builder\nic1.vmx-part
GOTO NIC1DONE

:NIC1D
echo ethernet1.present = "TRUE"  > %temp%\vmx-builder\nic1.vmx-part
echo ethernet1.vnet =  "VMnet3" >> %temp%\vmx-builder\nic1.vmx-part
GOTO NIC1DONE

:NIC1E
echo ethernet1.present = "TRUE"  > %temp%\vmx-builder\nic1.vmx-part
echo ethernet1.vnet =  "VMnet4" >> %temp%\vmx-builder\nic1.vmx-part
GOTO NIC1DONE

:NIC1F
echo ethernet1.present = "TRUE"  > %temp%\vmx-builder\nic1.vmx-part
echo ethernet1.vnet =  "VMnet5" >> %temp%\vmx-builder\nic1.vmx-part
GOTO NIC1DONE

:NIC1G
echo ethernet1.present = "TRUE"  > %temp%\vmx-builder\nic1.vmx-part
echo ethernet1.vnet =  "VMnet6" >> %temp%\vmx-builder\nic1.vmx-part
GOTO NIC1DONE

:NIC1H
echo ethernet1.present = "TRUE"  > %temp%\vmx-builder\nic1.vmx-part
echo ethernet1.vnet =  "VMnet7" >> %temp%\vmx-builder\nic1.vmx-part
GOTO NIC1DONE

:NIC1I
echo ethernet1.present = "TRUE"  > %temp%\vmx-builder\nic1.vmx-part
echo ethernet1.vnet =  "VMnet8" >> %temp%\vmx-builder\nic1.vmx-part
GOTO NIC1DONE

:NIC1J
echo ethernet1.present = "TRUE"  > %temp%\vmx-builder\nic1.vmx-part
echo ethernet1.vnet =  "VMnet9" >> %temp%\vmx-builder\nic1.vmx-part
GOTO NIC1DONE

:NIC1DONE

:NIC2SET

SET Choice=

echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.
echo      Lets talk about ethernet2
echo.
echo      x = NIC 2 - no ... thanks
echo      0 = give me one in vmnet0
echo      1 = give me one in vmnet1
echo      2 = give me one in vmnet2
echo      3 = give me one in vmnet3
echo      4 = give me one in vmnet4
echo      5 = give me one in vmnet5
echo      6 = give me one in vmnet6
echo      7 = give me one in vmnet7
echo      8 = give me one in vmnet8
echo      9 = give me one in vmnet9
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="x"    GOTO DEVICES
IF /I "%Choice%"=="0"    GOTO NIC2A
IF /I "%Choice%"=="1"    GOTO NIC2B
IF /I "%Choice%"=="2"    GOTO NIC2C
IF /I "%Choice%"=="3"    GOTO NIC2D
IF /I "%Choice%"=="4"    GOTO NIC2E
IF /I "%Choice%"=="5"    GOTO NIC2F
IF /I "%Choice%"=="6"    GOTO NIC2G
IF /I "%Choice%"=="7"    GOTO NIC2H
IF /I "%Choice%"=="8"    GOTO NIC2I
IF /I "%Choice%"=="9"    GOTO NIC2J

ECHO "%Choice%" is not valid. Please try again.
pause
GOTO NIC2SET
:NIC2X
echo ethernet2.present = "FALSE" > %temp%\vmx-builder\nic2.vmx-part
GOTO NIC2DONE
:NIC2A
echo ethernet2.present = "TRUE"  > %temp%\vmx-builder\nic2.vmx-part
echo ethernet2.vnet =  "VMnet0" >> %temp%\vmx-builder\nic2.vmx-part
GOTO NIC2DONE
:NIC2B
echo ethernet2.present = "TRUE"  > %temp%\vmx-builder\nic2.vmx-part 
echo ethernet2.vnet =  "VMnet1" >> %temp%\vmx-builder\nic2.vmx-part 
GOTO NIC2DONE
:NIC2C
echo ethernet2.present = "TRUE"  > %temp%\vmx-builder\nic2.vmx-part 
echo ethernet2.vnet =  "VMnet2" >> %temp%\vmx-builder\nic2.vmx-part 
GOTO NIC2DONE
:NIC2D
echo ethernet2.present = "TRUE"  > %temp%\vmx-builder\nic2.vmx-part 
echo ethernet2.vnet =  "VMnet3" >> %temp%\vmx-builder\nic2.vmx-part 
GOTO NIC2DONE
:NIC2E
echo ethernet2.present = "TRUE"  > %temp%\vmx-builder\nic2.vmx-part 
echo ethernet2.vnet =  "VMnet4" >> %temp%\vmx-builder\nic2.vmx-part 
GOTO NIC2DONE
:NIC2F
echo ethernet2.present = "TRUE"  > %temp%\vmx-builder\nic2.vmx-part 
echo ethernet2.vnet =  "VMnet5" >> %temp%\vmx-builder\nic2.vmx-part 
GOTO NIC2DONE
:NIC2G
echo ethernet2.present = "TRUE"  > %temp%\vmx-builder\nic2.vmx-part 
echo ethernet2.vnet =  "VMnet6" >> %temp%\vmx-builder\nic2.vmx-part 
GOTO NIC2DONE
:NIC2H
echo ethernet2.present = "TRUE"  > %temp%\vmx-builder\nic2.vmx-part 
echo ethernet2.vnet =  "VMnet7" >> %temp%\vmx-builder\nic2.vmx-part 
GOTO NIC2DONE
:NIC2I
echo ethernet2.present = "TRUE"  > %temp%\vmx-builder\nic2.vmx-part 
echo ethernet2.vnet =  "VMnet8" >> %temp%\vmx-builder\nic2.vmx-part 
GOTO NIC2DONE
:NIC2J
echo ethernet2.present = "TRUE"  > %temp%\vmx-builder\nic2.vmx-part 
echo ethernet2.vnet =  "VMnet9" >> %temp%\vmx-builder\nic2.vmx-part 
GOTO NIC2DONE
:NIC2DONE

:NIC3SET
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.
echo      Lets talk about ethernet3
echo.
echo      x = NIC 3 - no ... thanks
echo      0 = give me one in vmnet0
echo      1 = give me one in vmnet1
echo      2 = give me one in vmnet2
echo      3 = give me one in vmnet3
echo      4 = give me one in vmnet4
echo      5 = give me one in vmnet5
echo      6 = give me one in vmnet6
echo      7 = give me one in vmnet7
echo      8 = give me one in vmnet8
echo      9 = give me one in vmnet9
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="x"    GOTO DEVICES
IF /I "%Choice%"=="0"    GOTO NIC3A
IF /I "%Choice%"=="1"    GOTO NIC3B
IF /I "%Choice%"=="2"    GOTO NIC3C
IF /I "%Choice%"=="3"    GOTO NIC3D
IF /I "%Choice%"=="4"    GOTO NIC3E
IF /I "%Choice%"=="5"    GOTO NIC3F
IF /I "%Choice%"=="6"    GOTO NIC3G
IF /I "%Choice%"=="7"    GOTO NIC3H
IF /I "%Choice%"=="8"    GOTO NIC3I
IF /I "%Choice%"=="9"    GOTO NIC3J
ECHO "%Choice%" is not valid. Please try again.
pause
GOTO NIC3SET
:NIC3X
echo ethernet3.present = "FALSE" > %temp%\vmx-builder\nic3.vmx-part
GOTO NIC3DONE
:NIC3A
echo ethernet3.present = "TRUE"  > %temp%\vmx-builder\nic3.vmx-part 
echo ethernet3.vnet =  "VMnet0" >> %temp%\vmx-builder\nic3.vmx-part 
GOTO NIC3DONE
:NIC3B
echo ethernet3.present = "TRUE"  > %temp%\vmx-builder\nic3.vmx-part 
echo ethernet3.vnet =  "VMnet1" >> %temp%\vmx-builder\nic3.vmx-part 
GOTO NIC3DONE
:NIC3C
echo ethernet3.present = "TRUE"  > %temp%\vmx-builder\nic3.vmx-part 
echo ethernet3.vnet =  "VMnet2" >> %temp%\vmx-builder\nic3.vmx-part 
GOTO NIC3DONE
:NIC3D
echo ethernet3.present = "TRUE"  > %temp%\vmx-builder\nic3.vmx-part 
echo ethernet3.vnet =  "VMnet3" >> %temp%\vmx-builder\nic3.vmx-part 
GOTO NIC3DONE
:NIC3E
echo ethernet3.present = "TRUE"  > %temp%\vmx-builder\nic3.vmx-part 
echo ethernet3.vnet =  "VMnet4" >> %temp%\vmx-builder\nic3.vmx-part 
GOTO NIC3DONE
:NIC3F
echo ethernet3.present = "TRUE"  > %temp%\vmx-builder\nic3.vmx-part 
echo ethernet3.vnet =  "VMnet5" >> %temp%\vmx-builder\nic3.vmx-part 
GOTO NIC3DONE
:NIC3G
echo ethernet3.present = "TRUE"  > %temp%\vmx-builder\nic3.vmx-part 
echo ethernet3.vnet =  "VMnet6" >> %temp%\vmx-builder\nic3.vmx-part 
GOTO NIC3DONE
:NIC3H
echo ethernet3.present = "TRUE"  > %temp%\vmx-builder\nic3.vmx-part 
echo ethernet3.vnet =  "VMnet7" >> %temp%\vmx-builder\nic3.vmx-part 
GOTO NIC3DONE
:NIC3I
echo ethernet3.present = "TRUE"  > %temp%\vmx-builder\nic3.vmx-part 
echo ethernet3.vnet =  "VMnet8" >> %temp%\vmx-builder\nic3.vmx-part 
GOTO NIC3DONE
:NIC3J
echo ethernet3.present = "TRUE"  > %temp%\vmx-builder\nic3.vmx-part 
echo ethernet3.vnet =  "VMnet9" >> %temp%\vmx-builder\nic3.vmx-part 
GOTO NIC3DONE
:NIC3DONE
GOTO DEVICES

:NICADVANCED
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo      0 = ethernet0 uses amd
echo      1 = ethernet0 uses vmxnet
echo      a = ethernet0 uses e1000 (WS 5.5 only)
echo.
echo      2 = ethernet1 uses amd
echo      3 = ethernet1 uses vmxnet
echo      b = ethernet1 uses e1000 (WS 5.5 only)
echo.
echo      4 = ethernet2 uses amd
echo      5 = ethernet2 uses vmxnet
echo      c = ethernet2 uses e1000 (WS 5.5 only)
echo.
echo      6 = ethernet3 uses amd
echo      7 = ethernet3 uses vmxnet
echo      d = ethernet0 uses e1000 (WS 5.5 only)
echo.
echo      x = done 
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="0"    GOTO NICADVANCED0
IF /I "%Choice%"=="1"    GOTO NICADVANCED1
IF /I "%Choice%"=="2"    GOTO NICADVANCED2
IF /I "%Choice%"=="3"    GOTO NICADVANCED3
IF /I "%Choice%"=="4"    GOTO NICADVANCED4
IF /I "%Choice%"=="5"    GOTO NICADVANCED5
IF /I "%Choice%"=="6"    GOTO NICADVANCED6
IF /I "%Choice%"=="7"    GOTO NICADVANCED7
IF /I "%Choice%"=="a"    GOTO NICADVANCEDa
IF /I "%Choice%"=="b"    GOTO NICADVANCEDb
IF /I "%Choice%"=="c"    GOTO NICADVANCEDc
IF /I "%Choice%"=="d"    GOTO NICADVANCEDd
IF /I "%Choice%"=="x"    GOTO NICADVANCEDx
ECHO "%Choice%" is not valid. Please try again.
pause
GOTO NICADVANCED
:NICADVANCED0
echo ethernet0.virtualDev = "vlance" > %temp%\vmx-builder\nic0type.vmx-part
GOTO NICADVANCED
:NICADVANCED1
echo ethernet0.virtualDev = "vmXnet" > %temp%\vmx-builder\nic0type.vmx-part
GOTO NICADVANCED
:NICADVANCEDa
echo ethernet0.virtualDev = "e1000" > %temp%\vmx-builder\nic0type.vmx-part
GOTO NICADVANCED
:NICADVANCED2
echo ethernet1.virtualDev = "vlance" > %temp%\vmx-builder\nic1type.vmx-part
GOTO NICADVANCED
:NICADVANCED3
echo ethernet1.virtualDev = "vmXnet" > %temp%\vmx-builder\nic1type.vmx-part
GOTO NICADVANCED
:NICADVANCEDb
echo ethernet1.virtualDev = "e1000" > %temp%\vmx-builder\nic1type.vmx-part
GOTO NICADVANCED
:NICADVANCED4
echo ethernet2.virtualDev = "vlance" > %temp%\vmx-builder\nic2type.vmx-part
GOTO NICADVANCED
:NICADVANCED5
echo ethernet2.virtualDev = "vmXnet" > %temp%\vmx-builder\nic2type.vmx-part
GOTO NICADVANCED
:NICADVANCEDc
echo ethernet2.virtualDev = "e1000" > %temp%\vmx-builder\nic2type.vmx-part
GOTO NICADVANCED
:NICADVANCED6
echo ethernet3.virtualDev = "vlance" > %temp%\vmx-builder\nic3type.vmx-part
GOTO NICADVANCED
:NICADVANCED7
echo ethernet3.virtualDev = "vmXnet" > %temp%\vmx-builder\nic3type.vmx-part
GOTO NICADVANCED
:NICADVANCEDd
echo ethernet3.virtualDev = "e1000" > %temp%\vmx-builder\nic3type.vmx-part
GOTO NICADVANCED
:NICADVANCEDx
GOTO DEVICES



:ADDIDE
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo      Add a virtual disk as IDE
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.     
echo     Make sure you select the *.vmdk
echo.
echo.
echo     x = exit
echo.
echo.  
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="" GOTO ADDIDE
IF /I "%Choice%"=="x" GOTO DEVICES   
if not exist %Choice% GOTO ADDIDE
set ide2add=%Choice%
GOTO ADDIDEDONE 

:ADDIDEDONE 
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo     Please select the port you want to use
echo.     
echo     0 = primary master
echo     1 = primary master
echo     2 = secondary master
echo     3 = secondary master
echo.
echo.
echo     x = not assigned
echo.
echo.  
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="" GOTO ADDIDEDONE 
IF /I "%Choice%"=="0" GOTO ADDIDEDONE0 
IF /I "%Choice%"=="1" GOTO ADDIDEDONE1 
IF /I "%Choice%"=="2" GOTO ADDIDEDONE2 
IF /I "%Choice%"=="3" GOTO ADDIDEDONE3 
IF /I "%Choice%"=="x" GOTO IDE01NA      
if not exist %Choice% GOTO IDE01NOTFOUND
echo ide0:1.present = "TRUE" > %temp%\vmx-builder\ide01.vmx-part
echo ide0:1.fileName = "%ide2add%" >> %temp%\vmx-builder\ide01.vmx-part
GOTO IDE00DONE         
:ADDIDEDONE0 
echo ide0:0.present = "TRUE" > %temp%\vmx-builder\ide00.vmx-part 
echo ide0:0.fileName = "%ide2add%" >> %temp%\vmx-builder\ide00.vmx-part   
GOTO DEVICES
:ADDIDEDONE1 
echo ide0:1.present = "TRUE" > %temp%\vmx-builder\ide01.vmx-part 
echo ide0:1.fileName = "%ide2add%" >> %temp%\vmx-builder\ide01.vmx-part   
GOTO DEVICES
:ADDIDEDONE2 
echo ide1:0.present = "TRUE" > %temp%\vmx-builder\ide10.vmx-part 
echo ide1:0.fileName = "%ide2add%" >> %temp%\vmx-builder\ide10.vmx-part   
GOTO DEVICES
:ADDIDEDONE3 
echo ide1:1.present = "TRUE" > %temp%\vmx-builder\ide11.vmx-part 
echo ide1:1.fileName = "%ide2add%" >> %temp%\vmx-builder\ide11.vmx-part   
GOTO DEVICES

:ADDCDROM
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo      Add an iso-file as virtual CDrom-drive
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.     
echo     Make sure you select an *.iso file
echo.
echo.
echo     x = exit
echo.
echo.  
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="" GOTO ADDCDROM
IF /I "%Choice%"=="x" GOTO DEVICES   
if not exist %Choice% GOTO ADDCDROM
set iso2add=%Choice%
GOTO ADDCDROMDONE 
:ADDCDROMDONE 
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo     Please select the IDE-port you want to use
echo.     
echo     0 = primary master      not connected at boot  
echo     1 = primary slave       not connected at boot
echo     2 = secondary master    not connected at boot
echo     3 = secondary slave     not connected at boot
echo     4 = primary master          connected at boot  
echo     5 = primary slave           connected at boot
echo     6 = secondary master        connected at boot
echo     7 = secondary slave         connected at boot
echo.
echo.
echo     x = exit
echo.
echo.  
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="" GOTO ADDCDROMDONE 
IF /I "%Choice%"=="0" GOTO ADDCDROMDONE0 
IF /I "%Choice%"=="1" GOTO ADDCDROMDONE1 
IF /I "%Choice%"=="2" GOTO ADDCDROMDONE2 
IF /I "%Choice%"=="3" GOTO ADDCDROMDONE3 
IF /I "%Choice%"=="4" GOTO ADDCDROMDONE4 
IF /I "%Choice%"=="5" GOTO ADDCDROMDONE5 
IF /I "%Choice%"=="6" GOTO ADDCDROMDONE6 
IF /I "%Choice%"=="7" GOTO ADDCDROMDONE7 
IF /I "%Choice%"=="x" GOTO DEVICES      
if not exist %Choice% GOTO ADDCDROM        
:ADDCDROMDONE0 
echo ide0:0.present = "TRUE" 		 > %temp%\vmx-builder\ide00.vmx-part 
echo ide0:0.fileName = "%iso2add%" 	>> %temp%\vmx-builder\ide00.vmx-part   
echo ide0:0.deviceType =  "cdrom-image" >> %temp%\vmx-builder\ide00.vmx-part 
echo ide0:0.startConnected = "FALSE" 	>> %temp%\vmx-builder\ide00.vmx-part 
GOTO DEVICES
:ADDCDROMDONE1 
echo ide0:1.present = "TRUE" 		 > %temp%\vmx-builder\ide01.vmx-part 
echo ide0:1.fileName = "%iso2add%" 	>> %temp%\vmx-builder\ide01.vmx-part   
echo ide0:1.deviceType =  "cdrom-image" >> %temp%\vmx-builder\ide01.vmx-part 
echo ide0:1.startConnected = "FALSE" 	>> %temp%\vmx-builder\ide01.vmx-part 
GOTO DEVICES
:ADDCDROMDONE2 
echo ide1:0.present = "TRUE" 		 > %temp%\vmx-builder\ide10.vmx-part 
echo ide1:0.fileName = "%iso2add%" 	>> %temp%\vmx-builder\ide10.vmx-part   
echo ide1:0.deviceType =  "cdrom-image" >> %temp%\vmx-builder\ide10.vmx-part 
echo ide1:0.startConnected = "FALSE" 	>> %temp%\vmx-builder\ide10.vmx-part 
GOTO DEVICES
:ADDCDROMDONE3 
echo ide1:1.present = "TRUE" 		 > %temp%\vmx-builder\ide11.vmx-part 
echo ide1:1.fileName = "%iso2add%" 	>> %temp%\vmx-builder\ide11.vmx-part   
echo ide1:1.deviceType =  "cdrom-image" >> %temp%\vmx-builder\ide11.vmx-part 
echo ide1:1.startConnected = "FALSE" 	>> %temp%\vmx-builder\ide11.vmx-part 
GOTO DEVICES
:ADDCDROMDONE4 
echo ide0:0.present = "TRUE" 		 > %temp%\vmx-builder\ide00.vmx-part 
echo ide0:0.fileName = "%iso2add%" 	>> %temp%\vmx-builder\ide00.vmx-part   
echo ide0:0.deviceType =  "cdrom-image" >> %temp%\vmx-builder\ide00.vmx-part 
echo ide0:0.startConnected = "TRUE"  	>> %temp%\vmx-builder\ide00.vmx-part 
GOTO DEVICES
:ADDCDROMDONE5 
echo ide0:1.present = "TRUE" 		 > %temp%\vmx-builder\ide01.vmx-part 
echo ide0:1.fileName = "%iso2add%" 	>> %temp%\vmx-builder\ide01.vmx-part   
echo ide0:1.deviceType =  "cdrom-image" >> %temp%\vmx-builder\ide01.vmx-part 
echo ide0:1.startConnected = "TRUE"  	>> %temp%\vmx-builder\ide01.vmx-part 
GOTO DEVICES
:ADDCDROMDONE6 
echo ide1:0.present = "TRUE" 		 > %temp%\vmx-builder\ide10.vmx-part 
echo ide1:0.fileName = "%iso2add%" 	>> %temp%\vmx-builder\ide10.vmx-part   
echo ide1:0.deviceType =  "cdrom-image" >> %temp%\vmx-builder\ide10.vmx-part 
echo ide1:0.startConnected = "TRUE" 	>> %temp%\vmx-builder\ide10.vmx-part 
GOTO DEVICES
:ADDCDROMDONE7 
echo ide1:1.present = "TRUE" 		 > %temp%\vmx-builder\ide11.vmx-part 
echo ide1:1.fileName = "%iso2add%" 	>> %temp%\vmx-builder\ide11.vmx-part   
echo ide1:1.deviceType =  "cdrom-image" >> %temp%\vmx-builder\ide11.vmx-part 
echo ide1:1.startConnected = "TRUE" 	>> %temp%\vmx-builder\ide11.vmx-part 
GOTO DEVICES

:FLOPPY
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo      0 = floppy 0  enabled
echo      1 = floppy 0  disabled
echo.
echo      2 = floppy 0  present at boot-time 
echo      3 = floppy 0  not present at boot-time
echo.
echo      4 = floppy 1  enabled
echo      5 = floppy 1  disabled
echo.              
echo      6 = floppy 1  present at boot-time 
echo      7 = floppy 1  not present at boot-time
echo.
echo      x = done 
echo.
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="0"    GOTO FLOPPY0
IF /I "%Choice%"=="1"    GOTO FLOPPY1
IF /I "%Choice%"=="2"    GOTO FLOPPY2
IF /I "%Choice%"=="3"    GOTO FLOPPY3
IF /I "%Choice%"=="4"    GOTO FLOPPY4
IF /I "%Choice%"=="5"    GOTO FLOPPY5
IF /I "%Choice%"=="6"    GOTO FLOPPY6
IF /I "%Choice%"=="7"    GOTO FLOPPY7
IF /I "%Choice%"=="x"    GOTO FLOPPYx

ECHO "%Choice%" is not valid. Please try again.
pause
GOTO FLOPPY
:FLOPPY0
echo floppy0.present = "TRUE" > %temp%\vmx-builder\floppy0.vmx-part
GOTO FLOPPY 
:FLOPPY1
echo floppy0.present = "FALSE" > %temp%\vmx-builder\floppy0.vmx-part
GOTO FLOPPY
:FLOPPY2
echo floppy0.startConnected = "TRUE" > %temp%\vmx-builder\floppy0boot.vmx-part
GOTO FLOPPY  
:FLOPPY3
echo floppy0.startConnected = "FALSE" > %temp%\vmx-builder\floppy0boot.vmx-part
GOTO FLOPPY
:FLOPPY4
echo floppy1.present = "TRUE" > %temp%\vmx-builder\floppy1.vmx-part
GOTO FLOPPY
:FLOPPY5
echo floppy1.present = "FALSE" > %temp%\vmx-builder\floppy1.vmx-part
GOTO FLOPPY 
:FLOPPY6
echo floppy1.startConnected = "TRUE" > %temp%\vmx-builder\floppy1boot.vmx-part
GOTO FLOPPY
:FLOPPY7
echo floppy1.startConnected = "FALSE" > %temp%\vmx-builder\floppy1boot.vmx-part
GOTO FLOPPY

:FLOPPYx  
GOTO DEVICES


:OSTYPE55 
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo    Please select the Operating System (Workstation 5.5)
echo.
echo    00 = other               19 = other26xlinux    37 = winNetBusiness     
echo    01 = darwin              20 = other24xlinux    38 = winNetEnterprise-64     
echo    02 = other-64            21 = ubuntu-64        39 = winNetEnterprise        
echo    03 = freeBSD-64          22 = ubuntu           40 = winNetStandard-64       
echo    04 = freeBSD             23 = turbolinux       41 = winNetStandard          
echo    05 = solaris10-64        24 = mandrake         42 = winNetWeb               
echo    06 = solaris10           25 = sles-64          43 = winXPPro-64             
echo    07 = solaris9            26 = suse-64          44 = winXPPro                
echo    08 = solaris8            27 = rhel4-64         45 = winXPHome               
echo    09 = solaris7            28 = rhel4            46 = win2000AdvServ          
echo    10 = solaris6            29 = rhel3-64         47 = win2000Serv             
echo    11 = netware6            30 = rhel3            48 = win2000Pro              
echo    12 = netware5            31 = rhel2            49 = winNT                   
echo    13 = netware4            32 = redhat           50 = winMe                   
echo    14 = linux               33 = winVista-64      51 = win98                   
echo    15 = otherlinux-64       34 = winVista         52 = win95                   
echo    16 = other26xlinux-64    35 = longhorn-64      53 = win31                   
echo    17 = other24xlinux-64    36 = longhorn         54 = dos      
echo    18 = otherlinux          36 = longhorn            

SET /P Choice=   
IF /I "%Choice%"=="00" GOTO OSTYPE5500
IF /I "%Choice%"=="01" GOTO OSTYPE5501
IF /I "%Choice%"=="02" GOTO OSTYPE5502
IF /I "%Choice%"=="03" GOTO OSTYPE5503
IF /I "%Choice%"=="04" GOTO OSTYPE5504
IF /I "%Choice%"=="05" GOTO OSTYPE5505
IF /I "%Choice%"=="06" GOTO OSTYPE5506
IF /I "%Choice%"=="07" GOTO OSTYPE5507
IF /I "%Choice%"=="08" GOTO OSTYPE5508
IF /I "%Choice%"=="09" GOTO OSTYPE5509
IF /I "%Choice%"=="10" GOTO OSTYPE5510
IF /I "%Choice%"=="11" GOTO OSTYPE5511
IF /I "%Choice%"=="12" GOTO OSTYPE5512
IF /I "%Choice%"=="13" GOTO OSTYPE5513
IF /I "%Choice%"=="14" GOTO OSTYPE5514
IF /I "%Choice%"=="15" GOTO OSTYPE5515
IF /I "%Choice%"=="16" GOTO OSTYPE5516
IF /I "%Choice%"=="17" GOTO OSTYPE5517
IF /I "%Choice%"=="18" GOTO OSTYPE5518
IF /I "%Choice%"=="19" GOTO OSTYPE5519
IF /I "%Choice%"=="20" GOTO OSTYPE5520
IF /I "%Choice%"=="21" GOTO OSTYPE5521
IF /I "%Choice%"=="22" GOTO OSTYPE5522
IF /I "%Choice%"=="23" GOTO OSTYPE5523
IF /I "%Choice%"=="24" GOTO OSTYPE5524
IF /I "%Choice%"=="25" GOTO OSTYPE5525
IF /I "%Choice%"=="26" GOTO OSTYPE5526
IF /I "%Choice%"=="27" GOTO OSTYPE5527
IF /I "%Choice%"=="28" GOTO OSTYPE5528
IF /I "%Choice%"=="29" GOTO OSTYPE5529
IF /I "%Choice%"=="30" GOTO OSTYPE5530
IF /I "%Choice%"=="31" GOTO OSTYPE5531
IF /I "%Choice%"=="32" GOTO OSTYPE5532
IF /I "%Choice%"=="33" GOTO OSTYPE5533
IF /I "%Choice%"=="34" GOTO OSTYPE5534
IF /I "%Choice%"=="35" GOTO OSTYPE5535
IF /I "%Choice%"=="36" GOTO OSTYPE5536
IF /I "%Choice%"=="37" GOTO OSTYPE5537
IF /I "%Choice%"=="38" GOTO OSTYPE5538
IF /I "%Choice%"=="39" GOTO OSTYPE5539
IF /I "%Choice%"=="40" GOTO OSTYPE5540
IF /I "%Choice%"=="41" GOTO OSTYPE5541
IF /I "%Choice%"=="42" GOTO OSTYPE5542
IF /I "%Choice%"=="43" GOTO OSTYPE5543
IF /I "%Choice%"=="44" GOTO OSTYPE5544
IF /I "%Choice%"=="45" GOTO OSTYPE5545
IF /I "%Choice%"=="46" GOTO OSTYPE5546
IF /I "%Choice%"=="47" GOTO OSTYPE5547
IF /I "%Choice%"=="48" GOTO OSTYPE5548
IF /I "%Choice%"=="49" GOTO OSTYPE5549
IF /I "%Choice%"=="50" GOTO OSTYPE5550
IF /I "%Choice%"=="51" GOTO OSTYPE5551
IF /I "%Choice%"=="52" GOTO OSTYPE5552
IF /I "%Choice%"=="53" GOTO OSTYPE5553     
IF /I "%Choice%"=="54" GOTO OSTYPE5554 



ECHO "%Choice%" is not valid. Please try again.
pause    
GOTO OSTYPE55   
:OSTYPE5500
echo guestOS = "dos"  > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE55DONE                                    
:OSTYPE5501
echo guestOS = "darwin"  > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE55DONE               
:OSTYPE5502
echo guestOS = "other-64"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5503
echo guestOS = "freeBSD-64"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5504
echo guestOS = "freeBSD" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5505
echo guestOS = "solaris10-64" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5506
echo guestOS = "solaris10"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE
:OSTYPE5507
echo guestOS = "solaris9"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5508
echo guestOS = "solaris8"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5509
echo guestOS = "solaris7"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5510
echo guestOS = "solaris6"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5511
echo guestOS = "netware6"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5512
echo guestOS = "netware5"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5513
echo guestOS = "netware4"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5514
echo guestOS = "linux"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5515
echo guestOS = "otherlinux-64"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5516
echo guestOS = "other26xlinux-64" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5517
echo guestOS = "other24xlinux-64" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5518
echo guestOS = "otherlinux"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5519
echo guestOS = "other26xlinux"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5520
echo guestOS = "other24xlinux"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5521
echo guestOS = "ubuntu-64" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5522
echo guestOS = "ubuntu"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE
:OSTYPE5523
echo guestOS = "turbolinux"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5524
echo guestOS = "mandrake"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5525
echo guestOS = "sles-64" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5526
echo guestOS = "suse-64" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5527
echo guestOS = "rhel4-64"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5528
echo guestOS = "rhel4"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5529
echo guestOS = "rhel3-64"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5530
echo guestOS = "rhel3"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5531
echo guestOS = "rhel2"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5532
echo guestOS = "redhat"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5533
echo guestOS = "winVista-64" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5534
echo guestOS = "winVista"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5535
echo guestOS = "longhorn-64" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5536
echo guestOS = "longhorn"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5537
echo guestOS = "winNetBusiness" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5538
echo guestOS = "winNetEnterprise-64" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5539
echo guestOS = "winNetEnterprise" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5540
echo guestOS = "winNetStandard-64"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5541
echo guestOS = "winNetStandard" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5542
echo guestOS = "winNetWeb" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5543
echo guestOS = "winXPPro-64" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5544
echo guestOS = "winXPPro"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5545
echo guestOS = "winXPHome" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5546
echo guestOS = "win2000AdvServ" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5547
echo guestOS = "win2000Serv" > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5548
echo guestOS = "win2000Pro"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5549
echo guestOS = "winNT"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5550
echo guestOS = "winMe"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5551
echo guestOS = "win98"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5552
echo guestOS = "win95"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5553
echo guestOS = "win31"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 
:OSTYPE5554
echo guestOS = "dos"  > %temp%\vmx-builder\guestOS.vmx-part 
GOTO OSTYPE55DONE 


:OSTYPE55DONE 
GOTO DEVICES

:OSTYPE50
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo    Please select the Operating System (Workstation 5.0)
echo.
echo    00 = other                        18 = rhel2
echo    01 = freeBSD                      19 = redhat
echo    02 = solaris10                    20 = longhorn
echo    03 = solaris9                     21 = winNetBusiness
echo    04 = solaris8                     22 = winNetEnterprise
echo    05 = solaris7                     23 = winNetStandard
echo    06 = solaris6                     24 = winNetWeb
echo    07 = netware6                     25 = winXPPro
echo    08 = netware5                     26 = winXPHome
echo    09 = netware4                     27 = win2000AdvServ
echo    10 = linux                        28 = win2000Serv
echo    11 = otherlinux                   29 = win2000Pro
echo    12 = other26xlinux                30 = winNT
echo    13 = other24xlinux                31 = winMe
echo    14 = turbolinux                   32 = win98
echo    15 = mandrake                     33 = win95
echo    16 = rhel4                        34 = win31
echo    17 = rhel3                        35 = msdos
echo.


SET /P Choice=
IF /I "%Choice%"=="00" GOTO OSTYPE5000
IF /I "%Choice%"=="01" GOTO OSTYPE5001
IF /I "%Choice%"=="02" GOTO OSTYPE5002
IF /I "%Choice%"=="03" GOTO OSTYPE5003
IF /I "%Choice%"=="04" GOTO OSTYPE5004
IF /I "%Choice%"=="05" GOTO OSTYPE5005
IF /I "%Choice%"=="06" GOTO OSTYPE5006
IF /I "%Choice%"=="07" GOTO OSTYPE5007
IF /I "%Choice%"=="08" GOTO OSTYPE5008
IF /I "%Choice%"=="09" GOTO OSTYPE5009
IF /I "%Choice%"=="10" GOTO OSTYPE5010
IF /I "%Choice%"=="11" GOTO OSTYPE5011
IF /I "%Choice%"=="12" GOTO OSTYPE5012
IF /I "%Choice%"=="13" GOTO OSTYPE5013
IF /I "%Choice%"=="14" GOTO OSTYPE5014
IF /I "%Choice%"=="15" GOTO OSTYPE5015
IF /I "%Choice%"=="16" GOTO OSTYPE5016
IF /I "%Choice%"=="17" GOTO OSTYPE5017
IF /I "%Choice%"=="18" GOTO OSTYPE5018
IF /I "%Choice%"=="19" GOTO OSTYPE5019
IF /I "%Choice%"=="20" GOTO OSTYPE5020
IF /I "%Choice%"=="21" GOTO OSTYPE5021
IF /I "%Choice%"=="22" GOTO OSTYPE5022
IF /I "%Choice%"=="23" GOTO OSTYPE5023
IF /I "%Choice%"=="24" GOTO OSTYPE5024
IF /I "%Choice%"=="25" GOTO OSTYPE5025
IF /I "%Choice%"=="26" GOTO OSTYPE5026
IF /I "%Choice%"=="27" GOTO OSTYPE5027
IF /I "%Choice%"=="28" GOTO OSTYPE5028
IF /I "%Choice%"=="29" GOTO OSTYPE5029
IF /I "%Choice%"=="30" GOTO OSTYPE5030
IF /I "%Choice%"=="31" GOTO OSTYPE5031
IF /I "%Choice%"=="32" GOTO OSTYPE5032
IF /I "%Choice%"=="33" GOTO OSTYPE5033
IF /I "%Choice%"=="34" GOTO OSTYPE5034
IF /I "%Choice%"=="35" GOTO OSTYPE5035

ECHO "%Choice%" is not valid. Please try again.
pause
GOTO OSTYPE50
:OSTYPE5000
echo guestOS = "other"               > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5001
echo guestOS = "freeBSD"             > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5002
echo guestOS = "solaris10"           > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5003
echo guestOS = "solaris9"            > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5004
echo guestOS = "solaris8"            > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5005
echo guestOS = "solaris7"            > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5006
echo guestOS = "solaris6"            > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5007
echo guestOS = "netware6"            > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5008
echo guestOS = "netware5"            > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5009
echo guestOS = "netware4"            > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5010
echo guestOS = "linux"               > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5011
echo guestOS = "otherlinux"          > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5012
echo guestOS = "other26xlinux"       > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5013
echo guestOS = "other24xlinux"       > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5014
echo guestOS = "turbolinux"          > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5015
echo guestOS = "mandrake"            > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5016
echo guestOS = "rhel4"               > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5017
echo guestOS = "rhel3"               > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5018
echo guestOS = "rhel2"               > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5019
echo guestOS = "redhat"              > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5020
echo guestOS = "longhorn"            > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5021
echo guestOS = "winNetBusiness"      > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5022
echo guestOS = "winNetEnterprise"    > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5023
echo guestOS = "winNetStandard"      > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5024
echo guestOS = "winNetWeb"           > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5025
echo guestOS = "winXPPro"            > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE5026
echo guestOS = "winXPHome"           > %temp%\vmx-builder\guestOS.vmx-part
 GOTO OSTYPE50DONE
:OSTYPE5027
echo guestOS = "win2000AdvServ"      > %temp%\vmx-builder\guestOS.vmx-part
 GOTO OSTYPE50DONE
:OSTYPE5028
echo guestOS = "win2000Serv"         > %temp%\vmx-builder\guestOS.vmx-part
 GOTO OSTYPE50DONE
:OSTYPE5029
echo guestOS = "win2000Pro"          > %temp%\vmx-builder\guestOS.vmx-part
 GOTO OSTYPE50DONE
:OSTYPE5030
echo guestOS = "winNT"               > %temp%\vmx-builder\guestOS.vmx-part
 GOTO OSTYPE50DONE
:OSTYPE5031
echo guestOS = "winMe"               > %temp%\vmx-builder\guestOS.vmx-part
 GOTO OSTYPE50DONE
:OSTYPE5032
echo guestOS = "win98"               > %temp%\vmx-builder\guestOS.vmx-part
 GOTO OSTYPE50DONE
:OSTYPE5033
echo guestOS = "win95"               > %temp%\vmx-builder\guestOS.vmx-part
 GOTO OSTYPE50DONE
:OSTYPE5034
echo guestOS = "win31"               > %temp%\vmx-builder\guestOS.vmx-part
 GOTO OSTYPE50DONE
:OSTYPE5035
echo guestOS = "msdos"               > %temp%\vmx-builder\guestOS.vmx-part
GOTO OSTYPE50DONE
:OSTYPE50DONE
GOTO DEVICES


:ADDSCSI  
set scsi2add=
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo      Add a virtual disk as SCSI
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.     
echo     Make sure you select the *.vmdk
echo.
echo.
echo.
echo.
echo.  
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="" GOTO ADDSCSI   
if not exist %Choice% GOTO ADDSCSI 
set scsi2add=%Choice%
GOTO ADDSCSIID 
:ADDSCSIID  
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo     Please select the SCSI-ID you want to use
echo.     
echo     00 = connect to SCSI-ID 0.0            10 = connect toSCSI-ID 1.0
echo     01 = connect to SCSI-ID 0.1            11 = connect toSCSI-ID 1.1
echo     02 = connect to SCSI-ID 0.2            12 = connect toSCSI-ID 1.2
echo     03 = connect to SCSI-ID 0.3            13 = connect toSCSI-ID 1.3
echo     04 = connect to SCSI-ID 0.4            14 = connect toSCSI-ID 1.4
echo     05 = connect to SCSI-ID 0.5            15 = connect toSCSI-ID 1.5
echo     06 = connect to SCSI-ID 0.6            16 = connect toSCSI-ID 1.6
echo.
echo.
echo     x = exit
echo.
echo.  
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="" GOTO ADDSCSI 
IF /I "%Choice%"=="00" GOTO SCSIID00
IF /I "%Choice%"=="01" GOTO SCSIID01
IF /I "%Choice%"=="02" GOTO SCSIID02
IF /I "%Choice%"=="03" GOTO SCSIID03
IF /I "%Choice%"=="04" GOTO SCSIID04
IF /I "%Choice%"=="05" GOTO SCSIID05
IF /I "%Choice%"=="06" GOTO SCSIID06
IF /I "%Choice%"=="10" GOTO SCSIID10
IF /I "%Choice%"=="11" GOTO SCSIID11
IF /I "%Choice%"=="12" GOTO SCSIID12
IF /I "%Choice%"=="13" GOTO SCSIID13
IF /I "%Choice%"=="14" GOTO SCSIID14
IF /I "%Choice%"=="15" GOTO SCSIID15
IF /I "%Choice%"=="16" GOTO SCSIID16
IF /I "%Choice%"=="x" GOTO DEVICES     
if not exist %Choice% GOTO ADDSCSI
:SCSIID00 
echo scsi0:0.present = "TRUE" > %temp%\vmx-builder\scsi00.vmx-part 
echo scsi0:0.filename = "%scsi2add%" >> %temp%\vmx-builder\scsi00.vmx-part   
GOTO ADDSCSIDONE
:SCSIID01 
echo scsi0:1.present = "TRUE" > %temp%\vmx-builder\scsi01.vmx-part 
echo scsi0:1.filename = "%scsi2add%" >> %temp%\vmx-builder\scsi01.vmx-part   
GOTO ADDSCSIDONE
:SCSIID02 
echo scsi0:2.present = "TRUE" > %temp%\vmx-builder\scsi02.vmx-part 
echo scsi0:2.filename = "%scsi2add%" >> %temp%\vmx-builder\scsi02.vmx-part   
GOTO ADDSCSIDONE
:SCSIID03 
echo scsi0:3.present = "TRUE" > %temp%\vmx-builder\scsi03.vmx-part 
echo scsi0:3.filename = "%scsi2add%" >> %temp%\vmx-builder\scsi03.vmx-part   
GOTO ADDSCSIDONE
:SCSIID04 
echo scsi0:4.present = "TRUE" > %temp%\vmx-builder\scsi04.vmx-part 
echo scsi0:4.filename = "%scsi2add%" >> %temp%\vmx-builder\scsi04.vmx-part   
GOTO ADDSCSIDONE
:SCSIID05 
echo scsi0:5.present = "TRUE" > %temp%\vmx-builder\scsi05.vmx-part 
echo scsi0:5.filename = "%scsi2add%" >> %temp%\vmx-builder\scsi05.vmx-part   
GOTO ADDSCSIDONE
:SCSIID06 
echo scsi0:6.present = "TRUE" > %temp%\vmx-builder\scsi06.vmx-part 
echo scsi0:6.filename = "%scsi2add%" >> %temp%\vmx-builder\scsi06.vmx-part   
GOTO ADDSCSIDONE
:SCSIID10 
echo scsi1:0.present = "TRUE" > %temp%\vmx-builder\scsi10.vmx-part 
echo scsi1:0.filename = "%scsi2add%" >> %temp%\vmx-builder\scsi10.vmx-part   
GOTO ADDSCSIDONE
:SCSIID11 
echo scsi1:1.present = "TRUE" > %temp%\vmx-builder\scsi11.vmx-part 
echo scsi1:1.filename = "%scsi2add%" >> %temp%\vmx-builder\scsi11.vmx-part   
GOTO ADDSCSIDONE
:SCSIID12 
echo scsi1:2.present = "TRUE" > %temp%\vmx-builder\scsi12.vmx-part 
echo scsi1:2.filename = "%scsi2add%" >> %temp%\vmx-builder\scsi12.vmx-part   
GOTO ADDSCSIDONE
:SCSIID13 
echo scsi1:3.present = "TRUE" > %temp%\vmx-builder\scsi13.vmx-part 
echo scsi1:3.filename = "%scsi2add%" >> %temp%\vmx-builder\scsi13.vmx-part   
GOTO ADDSCSIDONE
:SCSIID14 
echo scsi1:4.present = "TRUE" > %temp%\vmx-builder\scsi14.vmx-part 
echo scsi1:4.filename = "%scsi2add%" >> %temp%\vmx-builder\scsi14.vmx-part   
GOTO ADDSCSIDONE
:SCSIID15 
echo scsi1:5.present = "TRUE" > %temp%\vmx-builder\scsi15.vmx-part 
echo scsi1:5.filename = "%scsi2add%" >> %temp%\vmx-builder\scsi15.vmx-part   
GOTO ADDSCSIDONE
:SCSIID16 
echo scsi1:6.present = "TRUE" > %temp%\vmx-builder\scsi16.vmx-part 
echo scsi1:6.filename = "%scsi2add%" >> %temp%\vmx-builder\scsi16.vmx-part   
GOTO ADDSCSIDONE
:ADDSCSIDONE
GOTO DEVICES


:CLUSTEROPTIONS
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.
echo      Options needed for clustering ...
echo.
echo.
echo.
echo      Warning: this is unsupported in Workstation and may not work
echo.
echo      You may need to edit used SCSI-IDs
echo.
echo.
echo.
echo      0 = add Clusteroptions
echo      x = exit
echo.
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="0"    GOTO :CLUSTEROPTIONS0
IF /I "%Choice%"=="x"    GOTO DEVICES
ECHO "%Choice%" is not valid. Please try again.
pause
GOTO CLUSTEROPTIONS



:CLUSTEROPTIONS0

echo ##### adding Cluster-options ###            > %temp%\vmx-builder\clusteroptions.vmx-part
echo disk.locking= "FALSE"                      >> %temp%\vmx-builder\clusteroptions.vmx-part
echo diskLib.dataCacheMaxSize = "0"             >> %temp%\vmx-builder\clusteroptions.vmx-part
echo diskLib.dataCacheMaxReadAheadSize = "0"    >> %temp%\vmx-builder\clusteroptions.vmx-part
echo diskLib.dataCacheMinReadAheadSize = "0"    >> %temp%\vmx-builder\clusteroptions.vmx-part
echo diskLib.dataCachePageSize = "4096"         >> %temp%\vmx-builder\clusteroptions.vmx-part
echo diskLib.maxUnsyncedWrites = "0"            >> %temp%\vmx-builder\clusteroptions.vmx-part
echo scsi0:0.sharedBus = "virtual"              >> %temp%\vmx-builder\clusteroptions.vmx-part
echo scsi0:0.mode = "independent-persistent"    >> %temp%\vmx-builder\clusteroptions.vmx-part
echo scsi0:0.deviceType = "plainDisk"           >> %temp%\vmx-builder\clusteroptions.vmx-part
echo scsi0:1.sharedBus = "virtual"              >> %temp%\vmx-builder\clusteroptions.vmx-part
echo scsi0:1.mode = "independent-persistent"    >> %temp%\vmx-builder\clusteroptions.vmx-part
echo scsi0:1.deviceType = "plainDisk"           >> %temp%\vmx-builder\clusteroptions.vmx-part
GOTO DEVICES

:CPU
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.
echo.     set SMP-options
echo. 
echo.
echo.     Don't try to add more CPUs than you got!
echo.
echo.
echo.
echo.
echo      0 = one  CPU
echo      1 = two  CPUs
echo      2 = four CPUs 
echo.
echo.
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="0"    GOTO CPU0
IF /I "%Choice%"=="1"    GOTO CPU1
IF /I "%Choice%"=="2"    GOTO CPU2
ECHO "%Choice%" is not valid. Please try again.
pause
GOTO CPU
:CPU0
echo numvcpus = "1" > %temp%\vmx-builder\cpu.vmx-part
GOTO DEVICES
:CPU1
echo numvcpus = "2" > %temp%\vmx-builder\cpu.vmx-part
GOTO DEVICES

:CPU2
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.   
echo.  
echo. 
echo.
echo     Nice try !
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo     ---------------------------------------------------------------
echo.
pause
GOTO CPU

:PORTS
SET Choice=
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo      0 = parallel port enabled
echo      1 = ethernet port disabled
echo.
echo      2 = serial port 0 enabled  
echo      3 = serial port 0 disabled 
echo.
echo      4 = serial port 1 enabled  
echo      5 = serial port 1 disabled 
echo.
echo.
echo.
echo      x = done 
echo.
echo.
echo.
echo     ---------------------------------------------------------------
echo.
SET /P Choice=
IF /I "%Choice%"=="0"    GOTO PORTS0
IF /I "%Choice%"=="1"    GOTO PORTS1
IF /I "%Choice%"=="2"    GOTO PORTS2
IF /I "%Choice%"=="3"    GOTO PORTS3
IF /I "%Choice%"=="4"    GOTO PORTS4
IF /I "%Choice%"=="5"    GOTO PORTS5
IF /I "%Choice%"=="x"    GOTO DEVICES

ECHO "%Choice%" is not valid. Please try again.
pause
GOTO PORTS

:PORTS0
echo parallel0.present = "TRUE" > %temp%\vmx-builder\parallel0.vmx-part
GOTO PORTS
:PORTS1
echo parallel0.present = "FALSE" > %temp%\vmx-builder\parallel0.vmx-part
GOTO PORTS
:PORTS2
echo serial0.present = "TRUE" > %temp%\vmx-builder\serial0.vmx-part
GOTO PORTS
:PORTS3
echo serial0.present =  "FALSE" > %temp%\vmx-builder\serial0.vmx-part
GOTO PORTS
:PORTS4
echo serial1.present = "TRUE" > %temp%\vmx-builder\serial1.vmx-part 
GOTO PORTS
:PORTS5
echo serial1.present = "FALSE" > %temp%\vmx-builder\serial1.vmx-part 
GOTO PORTS

:PREVIEW
echo #######################################  	>> %temp%\vmx-builder\preview.txt
echo ###### preview of %nicname%.vmx	  	 > %temp%\vmx-builder\preview.txt
echo ######                                   	>> %temp%\vmx-builder\preview.txt
echo ###### the latest state of the new       	>> %temp%\vmx-builder\preview.txt
echo ###### vmx-file is displayed             	>> %temp%\vmx-builder\preview.txt
echo ###### close window to continue          	>> %temp%\vmx-builder\preview.txt
echo ######                                   	>> %temp%\vmx-builder\preview.txt
echo #######################################  	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\new.vmx        		>> %temp%\vmx-builder\preview.txt 
type %temp%\vmx-builder\hw.vmx-part		>> %temp%\vmx-builder\preview.txt  
type %temp%\vmx-builder\ram.vmx-part         	>> %temp%\vmx-builder\preview.txt  
type %temp%\vmx-builder\cpu.vmx-part   		>> %temp%\vmx-builder\preview.txt  
type %temp%\vmx-builder\guestOS.vmx-part	>> %temp%\vmx-builder\preview.txt  
echo.						>> %temp%\vmx-builder\preview.txt
echo ####### ide-disks #####################  	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\ide00.vmx-part		>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\ide01.vmx-part       	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\ide10.vmx-part       	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\ide11.vmx-part		>> %temp%\vmx-builder\preview.txt
echo.						>> %temp%\vmx-builder\preview.txt
echo ####### scsi-controllers ##############  	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\scsi0.vmx-part      	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\scsi1.vmx-part      	>> %temp%\vmx-builder\preview.txt
echo.						>> %temp%\vmx-builder\preview.txt
echo ####### scsi-disks ####################  	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\scsi00.vmx-part      	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\scsi01.vmx-part      	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\scsi02.vmx-part      	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\scsi03.vmx-part      	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\scsi04.vmx-part      	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\scsi05.vmx-part      	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\scsi06.vmx-part		>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\scsi10.vmx-part      	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\scsi11.vmx-part      	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\scsi12.vmx-part      	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\scsi13.vmx-part      	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\scsi14.vmx-part      	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\scsi15.vmx-part      	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\scsi16.vmx-part      	>> %temp%\vmx-builder\preview.txt
echo.						>> %temp%\vmx-builder\preview.txt
echo ####### nics ##########################  	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\nic0.vmx-part        	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\nic0type.vmx-part	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\nic1.vmx-part        	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\nic1type.vmx-part    	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\nic2.vmx-part        	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\nic2type.vmx-part    	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\nic3.vmx-part        	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\nic3type.vmx-part    	>> %temp%\vmx-builder\preview.txt
echo.						>> %temp%\vmx-builder\preview.txt
echo ####### sound #########################  	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\sound.vmx-part       	>> %temp%\vmx-builder\preview.txt
echo.						>> %temp%\vmx-builder\preview.txt
echo ####### usb ###########################  	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\usb.vmx-part         	>> %temp%\vmx-builder\preview.txt
echo.						>> %temp%\vmx-builder\preview.txt
echo ####### floppies ######################  	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\floppy0.vmx-part        >> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\floppy0boot.vmx-part    >> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\floppy1.vmx-part        >> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\floppy1boot.vmx-part    >> %temp%\vmx-builder\preview.txt
echo.						>> %temp%\vmx-builder\preview.txt
echo ####### ports #########################  	>> %temp%\vmx-builder\preview.txt 
type %temp%\vmx-builder\parallel0.vmx-part	>> %temp%\vmx-builder\preview.txt     
type %temp%\vmx-builder\serial0.vmx-part        >> %temp%\vmx-builder\preview.txt 
type %temp%\vmx-builder\serial1.vmx-part        >> %temp%\vmx-builder\preview.txt 
echo.						>> %temp%\vmx-builder\preview.txt
echo ####### advanced stuff ################  	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\clusteroptions.vmx-part >> %temp%\vmx-builder\preview.txt 
type %temp%\vmx-builder\logging.vmx-part 	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\debug.vmx-part        	>> %temp%\vmx-builder\preview.txt 
type %temp%\vmx-builder\sharedfolders.vmx-part  >> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\dnd.vmx-part    	>> %temp%\vmx-builder\preview.txt
type %temp%\vmx-builder\copy.vmx-part        	>> %temp%\vmx-builder\preview.txt 
type %temp%\vmx-builder\paste.vmx-part  	>> %temp%\vmx-builder\preview.txt

echo ####### end of file ###################  	>> %temp%\vmx-builder\preview.txt
                                           
                                           
                                           
                                           
                                           
                                           
                                           
                                           

call notepad.exe %temp%\vmx-builder\preview.txt
GOTO DEVICES

:WRITE

echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo      writing the vmx-file to a temporary file and displaying it in notepad
echo.
echo      you can save and rename the vmx-file from within notepad ...
echo.
echo      Warning: this VMX-builder is unsupported by VMware
echo.
echo      Use the output on your own risk!
echo.
echo.
echo.
echo      (please check paths to vmdks, isos and other files if you move the vmx)
echo.
echo.
echo.
echo.
echo     ---------------------------------------------------------------
echo.
pause
echo ###### %nicname%.vmx  			 > %temp%\vmx-builder\%Nicname%.vmx
echo ######                                   	>> %temp%\vmx-builder\%Nicname%.vmx
echo ###### use copy and paste      		>> %temp%\vmx-builder\%Nicname%.vmx
echo ###### to export this file           	>> %temp%\vmx-builder\%Nicname%.vmx
echo ######                                   	>> %temp%\vmx-builder\%Nicname%.vmx
echo #######################################  	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\new.vmx        		>> %temp%\vmx-builder\%Nicname%.vmx 
type %temp%\vmx-builder\hw.vmx-part		>> %temp%\vmx-builder\%Nicname%.vmx  
type %temp%\vmx-builder\ram.vmx-part         	>> %temp%\vmx-builder\%Nicname%.vmx  
type %temp%\vmx-builder\cpu.vmx-part   		>> %temp%\vmx-builder\%Nicname%.vmx  
type %temp%\vmx-builder\guestOS.vmx-part	>> %temp%\vmx-builder\%Nicname%.vmx  
echo.						>> %temp%\vmx-builder\%Nicname%.vmx
echo ####### ide-disks #####################  	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\ide00.vmx-part		>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\ide01.vmx-part       	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\ide10.vmx-part       	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\ide11.vmx-part		>> %temp%\vmx-builder\%Nicname%.vmx
echo.						>> %temp%\vmx-builder\%Nicname%.vmx
echo ####### scsi-controllers ##############  	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\scsi0.vmx-part      	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\scsi1.vmx-part      	>> %temp%\vmx-builder\%Nicname%.vmx
echo.						>> %temp%\vmx-builder\%Nicname%.vmx
echo ####### scsi-disks ####################  	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\scsi00.vmx-part      	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\scsi01.vmx-part      	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\scsi02.vmx-part      	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\scsi03.vmx-part      	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\scsi04.vmx-part      	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\scsi05.vmx-part      	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\scsi06.vmx-part		>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\scsi10.vmx-part      	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\scsi11.vmx-part      	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\scsi12.vmx-part      	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\scsi13.vmx-part      	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\scsi14.vmx-part      	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\scsi15.vmx-part      	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\scsi16.vmx-part      	>> %temp%\vmx-builder\%Nicname%.vmx
echo.						>> %temp%\vmx-builder\%Nicname%.vmx
echo ####### nics ##########################  	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\nic0.vmx-part        	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\nic0type.vmx-part	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\nic1.vmx-part        	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\nic1type.vmx-part    	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\nic2.vmx-part        	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\nic2type.vmx-part    	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\nic3.vmx-part        	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\nic3type.vmx-part    	>> %temp%\vmx-builder\%Nicname%.vmx
echo.						>> %temp%\vmx-builder\%Nicname%.vmx
echo ####### sound #########################  	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\sound.vmx-part       	>> %temp%\vmx-builder\%Nicname%.vmx
echo.						>> %temp%\vmx-builder\%Nicname%.vmx
echo ####### usb ###########################  	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\usb.vmx-part         	>> %temp%\vmx-builder\%Nicname%.vmx
echo.						>> %temp%\vmx-builder\%Nicname%.vmx
echo ####### floppies ######################  	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\floppy0.vmx-part        >> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\floppy0boot.vmx-part    >> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\floppy1.vmx-part        >> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\floppy1boot.vmx-part    >> %temp%\vmx-builder\%Nicname%.vmx
echo.						>> %temp%\vmx-builder\%Nicname%.vmx
echo ####### ports #########################  	>> %temp%\vmx-builder\%Nicname%.vmx 
type %temp%\vmx-builder\parallel0.vmx-part	>> %temp%\vmx-builder\%Nicname%.vmx     
type %temp%\vmx-builder\serial0.vmx-part        >> %temp%\vmx-builder\%Nicname%.vmx 
type %temp%\vmx-builder\serial1.vmx-part        >> %temp%\vmx-builder\%Nicname%.vmx 
echo.						>> %temp%\vmx-builder\%Nicname%.vmx
echo ####### advanced stuff ################  	>> %temp%\vmx-builder\%Nicname%.vmx
type %temp%\vmx-builder\clusteroptions.vmx-part >> %temp%\vmx-builder\%Nicname%.vmx 
type %temp%\vmx-builder\logging.vmx-part 	>> %temp%\vmx-builder\%Nicname%.vmx 
type %temp%\vmx-builder\debug.vmx-part        	>> %temp%\vmx-builder\%Nicname%.vmx 
type %temp%\vmx-builder\sharedfolders.vmx-part  >> %temp%\vmx-builder\%Nicname%.vmx 
type %temp%\vmx-builder\dnd.vmx-part    	>> %temp%\vmx-builder\%Nicname%.vmx 
type %temp%\vmx-builder\copy.vmx-part        	>> %temp%\vmx-builder\%Nicname%.vmx 
type %temp%\vmx-builder\paste.vmx-part  	>> %temp%\vmx-builder\%Nicname%.vmx 

echo ####### end of file ###################  	>> %temp%\vmx-builder\%Nicname%.vmx 
del %temp%\vmx-builder\*.vmx-part     
del  %temp%\vmx-builder\new.vmx 
notepad   %temp%\vmx-builder\%Nicname%.vmx
explorer %temp%\vmx-builder\                                                                      
                                                                      
GOTO DEVICES                                                            
                                                 

:DONE
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo            Ullis VMX-builder is available at http://sanbarrow.com 
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo            Goodbye   
echo                                - and thanks for all the fish ...
echo.
echo.
echo.
echo.
echo     ---------------------------------------------------------------
echo.
sleep 5
 
GOTO GOODBYE
:GOODBYE
exit

:BULLSHIT
echo.
echo     ---SANBARROW.COM-----------------------------------------------
echo.
echo.
echo.
echo.
echo.
echo.                                                                          
echo        : :   : :   : ::::: :    : ::::     : :   : ::::: :   : :::::           
echo        : ::  : :   : :   : :    : :   :    : ::  : :   : :   :   :             
echo        : : : : :   : ::::: :    : :   :    : : : : ::::: :   :   :             
echo        : :  ::  : :  :   : :    : :   :    : :  :: :     :   :   :             
echo        : :   :   :   :   : :::: : ::::     : :   : :     :::::   :             
echo.                                                                                
echo.                                                                                
echo.                                                                                
echo.                                                                                
echo.                                                                                
pause
exit